#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# @name hexa_tilted_gps
# @copyright 2026 Robotsix
# @maintainer Damien SIX <damien@robotsix.net>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

# Disable DDS timestamp synchronization (UXRCE_DDS_SYNCT 0)
# In simulation, PX4 time is already aligned with simulator time.
# We don't want the DDS client to realign timestamps back to OS time.
param set-default UXRCE_DDS_SYNCT 0
param set-default UXRCE_DDS_SYNCC 0

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX 0.5
param set-default CA_ROTOR0_PY -0
param set-default CA_ROTOR0_PZ -0.01
param set-default CA_ROTOR0_AX 0.2588190451025207
param set-default CA_ROTOR0_AY -0
param set-default CA_ROTOR0_AZ -0.9659258262890683
param set-default CA_ROTOR0_CT 30.0
param set-default CA_ROTOR0_KM -0.01

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MAX1 1000

param set-default CA_ROTOR1_PX 0.2500000000000001
param set-default CA_ROTOR1_PY -0.4330127018922193
param set-default CA_ROTOR1_PZ -0.01
param set-default CA_ROTOR1_AX 0.1294095225512604
param set-default CA_ROTOR1_AY -0.2241438680420134
param set-default CA_ROTOR1_AZ -0.9659258262890683
param set-default CA_ROTOR1_CT 30.0
param set-default CA_ROTOR1_KM 0.01

param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MAX2 1000

param set-default CA_ROTOR2_PX -0.2499999999999999
param set-default CA_ROTOR2_PY -0.4330127018922194
param set-default CA_ROTOR2_PZ -0.01
param set-default CA_ROTOR2_AX -0.1294095225512603
param set-default CA_ROTOR2_AY -0.2241438680420134
param set-default CA_ROTOR2_AZ -0.9659258262890683
param set-default CA_ROTOR2_CT 30.0
param set-default CA_ROTOR2_KM -0.01

param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MAX3 1000

param set-default CA_ROTOR3_PX -0.5
param set-default CA_ROTOR3_PY -6.123233995736766e-17
param set-default CA_ROTOR3_PZ -0.01
param set-default CA_ROTOR3_AX -0.2588190451025207
param set-default CA_ROTOR3_AY -3.169619151431765e-17
param set-default CA_ROTOR3_AZ -0.9659258262890683
param set-default CA_ROTOR3_CT 30.0
param set-default CA_ROTOR3_KM 0.01

param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 0
param set-default SIM_GZ_EC_MAX4 1000

param set-default CA_ROTOR4_PX -0.2500000000000002
param set-default CA_ROTOR4_PY 0.4330127018922192
param set-default CA_ROTOR4_PZ -0.01
param set-default CA_ROTOR4_AX -0.1294095225512605
param set-default CA_ROTOR4_AY 0.2241438680420133
param set-default CA_ROTOR4_AZ -0.9659258262890683
param set-default CA_ROTOR4_CT 30.0
param set-default CA_ROTOR4_KM -0.01

param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_MIN5 0
param set-default SIM_GZ_EC_MAX5 1000

param set-default CA_ROTOR5_PX 0.2500000000000001
param set-default CA_ROTOR5_PY 0.4330127018922193
param set-default CA_ROTOR5_PZ -0.01
param set-default CA_ROTOR5_AX 0.1294095225512604
param set-default CA_ROTOR5_AY 0.2241438680420134
param set-default CA_ROTOR5_AZ -0.9659258262890683
param set-default CA_ROTOR5_CT 30.0
param set-default CA_ROTOR5_KM 0.01

param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_MIN6 0
param set-default SIM_GZ_EC_MAX6 1000

param set-default MPC_MANTHR_MIN 0.01
param set-default MPC_THR_MIN 0.01
param set-default MPC_THR_HOVER 0.2821

# Use squared motor control signal
param set-default THR_MDL_FAC 1

# PID tuning
param set-default MC_ROLLRATE_K 0.5
param set-default MC_PITCHRATE_K 0.5
param set-default MC_YAW_P 1.0

# In simulation, with no remote
param set-default COM_RC_IN_MODE 1 # Joystick
param set-default COM_OBL_RC_ACT 7
param set-default COM_OF_LOSS_T 1.0
param set-default COM_OBC_LOSS_T 1.0
param set-default NAV_RCL_ACT 0
param set-default NAV_DLL_ACT 0
param set-default COM_QC_ACT 0
param set-default GF_ACTION 0
param set-default COM_RC_OVERRIDE 0
param set-default COM_RCL_EXCEPT 7
param set-default COM_FAIL_ACT_T 0.0
param set-default FD_ACT_EN 0
param set-default FD_ESCS_EN 0
param set-default EKF2_REQ_VDRIFT 0.5
