#####
# This file maps all the topics that are to be used on the uXRCE-DDS client.
#####

publications:
  # Estimation and status topics
  - topic: /fmu/out/estimator_status
    type: px4_msgs::msg::EstimatorStatus
  - topic: /fmu/out/vehicle_land_detected
    type: px4_msgs::msg::VehicleLandDetected
  - topic: /fmu/out/failsafe_flags
    type: px4_msgs::msg::FailsafeFlags
  - topic: /fmu/out/vehicle_status
    type: px4_msgs::msg::VehicleStatus
  - topic: /fmu/out/vehicle_control_mode
    type: px4_msgs::msg::VehicleControlMode
  - topic: /fmu/out/timesync_status
    type: px4_msgs::msg::TimesyncStatus

  # Position and velocity topics
  - topic: /fmu/out/vehicle_local_position
    type: px4_msgs::msg::VehicleLocalPosition
  - topic: /fmu/out/vehicle_global_position
    type: px4_msgs::msg::VehicleGlobalPosition
  - topic: /fmu/out/vehicle_gps_position
    type: px4_msgs::msg::SensorGps
  - topic: /fmu/out/vehicle_odometry
    type: px4_msgs::msg::VehicleOdometry
  
  # Attitude and angular velocity topics
  - topic: /fmu/out/vehicle_acceleration
    type: px4_msgs::msg::VehicleAcceleration
  - topic: /fmu/out/vehicle_angular_velocity
    type: px4_msgs::msg::VehicleAngularVelocity
  - topic: /fmu/out/vehicle_attitude
    type: px4_msgs::msg::VehicleAttitude
  
  # Actuator topics
  - topic: /fmu/out/actuator_motors
    type: px4_msgs::msg::ActuatorMotors
  - topic: /fmu/out/vehicle_thrust_setpoint
    type: px4_msgs::msg::VehicleThrustSetpoint
  
  # Sensor topics
  - topic: /fmu/out/sensor_combined
    type: px4_msgs::msg::SensorCombined
  
  # Trajectory and planning topics
  - topic: /fmu/out/collision_constraints
    type: px4_msgs::msg::CollisionConstraints
  - topic: /fmu/out/position_setpoint_triplet
    type: px4_msgs::msg::PositionSetpointTriplet
  - topic: /fmu/out/vehicle_trajectory_waypoint_desired
    type: px4_msgs::msg::VehicleTrajectoryWaypoint

subscriptions:
  # Control mode topics
  - topic: /fmu/in/offboard_control_mode
    type: px4_msgs::msg::OffboardControlMode
  - topic: /fmu/in/vehicle_command
    type: px4_msgs::msg::VehicleCommand
  
  # Setpoint topics
  - topic: /fmu/in/trajectory_setpoint
    type: px4_msgs::msg::TrajectorySetpoint
  - topic: /fmu/in/vehicle_attitude_setpoint
    type: px4_msgs::msg::VehicleAttitudeSetpoint
  - topic: /fmu/in/vehicle_rates_setpoint
    type: px4_msgs::msg::VehicleRatesSetpoint
  
  # Trajectory topics
  - topic: /fmu/in/vehicle_trajectory_bezier
    type: px4_msgs::msg::VehicleTrajectoryBezier
  - topic: /fmu/in/vehicle_trajectory_waypoint
    type: px4_msgs::msg::VehicleTrajectoryWaypoint
  
  # Odometry topics
  - topic: /fmu/in/vehicle_mocap_odometry
    type: px4_msgs::msg::VehicleOdometry
  - topic: /fmu/in/vehicle_visual_odometry
    type: px4_msgs::msg::VehicleOdometry
  
  # Sensor and status topics
  - topic: /fmu/in/onboard_computer_status
    type: px4_msgs::msg::OnboardComputerStatus
  - topic: /fmu/in/obstacle_distance
    type: px4_msgs::msg::ObstacleDistance
  - topic: /fmu/in/sensor_optical_flow
    type: px4_msgs::msg::SensorOpticalFlow
  - topic: /fmu/in/telemetry_status
    type: px4_msgs::msg::TelemetryStatus
